\documentclass[pdftex,11pt]{article}
\usepackage{graphicx}
\usepackage{pdfpages}

\begin{document}
\begin{titlepage}
\begin{center}
\section* {MASENO UNIVERSITY}
\textsc{\large Department of Mathematics Acturial science and Statistics}\\[0.8cm]
(A report following attachment at KEMRI wellcome Trust between 8th September 2014 and 28th November 2014 submitted in partial fulfillment of a degree in BSC. Applied statistics with IT)  
\end{center}

\author\\
{JACKLINE AWINO OCHIEL}\\[0.5CM]
ADMISSION NO:MAT/00089/011\\[0.5CM]
CONTACT:0713300798\\[0.5CM]
COURSE: INDUSTRIAL ATTACHMENT\\[0.5CM]
CODE:SAS 317\\[0.8CM]
\section*{SUPERVISORS:}
%\end{center}

%\begin{flushleft}
1.UNIVERSITY SUPERVISOR:\\
MR.OMURUNDO\\[0.2cm]
CONTACT\\[0.2cm]
SIGNATURE\\[0.5cm]
2.KWTRP SUPERVISOR:
DR.GREG FEGAN\\[0.2cm]
CONTACT\\[0.2cm]
SIGNATURE\\
\end{titlepage}

%\section*{Abbreviations}
\section*{Abbreviations}
KWTRP......... KEMRI Wellcome Trust Research Program\\
KEMRI......... Kenya Medical Research Institute\\
EAMRC......... East African Medical Research Council\\
KHDSS......... Kilifi Health and Demographic Surveillance System\\
KIPMAT.........Kilifi Perinatal and Maternal Research Project\\
MOOC......... Massive Open Online Courses\\

\section*{Declaration}
I made all the efforts to ensure the accuracy of  information in this report,  the references mentioned are some of the resources from where I obtained information to come up with the report
\section*{Acknowledgment}
Am immensely grateful to KWTRP for giving me the chance to be an attachee in their institution and providing me with the facilities I used during my attachment. In particular, I sincerely acknowledge the head of statistics department, Dr. Greg Fegan for exposing me to useful statistical software and real data.  His advice and guidance was handy through my attachment. He is indeed a living legacy of excellence that will enrich the generation of young statisticians. \\ I would also like to acknowledge Maseno University department of statistics for their vast knowledge that helped me in my attachment. In particular, special regards to my supervisor Mr. Omurundo. I also acknowledge Amos and Ken, statisticians at KWTRP, for their endless assistance in handling statistical software. Finally, extend my heartfelt gratitude to Horace, quality assurances officer at KWTRP, for his constant encouragement and support that made my attachment a success.%\\[5.0cm]

  \section*  {Introduction}
The attachment took place from 8th September 2014 to 28th November 2014.This report outlines the background, administrative structure and programs run by KWTRP. It describes the duties I performed and details of skills I acquired from the institution. %It also explains the analysis I did and the presentation of the analysis.
\\[15.0cm]

\tableofcontents
\vspace{6.0cm}
\section { CHAPTER ONE}

\subsection{Historical Background of the Organization}


KEMRI was established following an amendment act in science and technology in 1979 to represent the national body responsible for conducting health science research in Kenya. Before its establishment health research was conducted by auspices of EAMRC which was established in 1957 to serve east African communities. \\ Kenyan parliament passed the science and technology Act in 1977 following the breakup of EAMRC, then amended it in 1979 to provide for establishment of research institutes.
 KWTRP is a partnership between KEMRI, Oxford University and Wellcome Trust established in 1989. It conducts basic  epidemiological and clinical research. It aims at expanding the country’s capacity to conduct multidisciplinary research that is strong, sustainable and internationally competitive.
%\begin{center}
\subsection*{Mission}

%\end{center}
To deliver high quality research relevant to global health and to build local capacity for undertaking research.
%\begin{center}

\subsection*{Vision}
%\end{center}
To establish long-term sustainable capacity for research in human health that improves global health.
%\begin{center}
\subsection{Location} 
%\end{center}
The Program has two main bases in Kenya but works in many other parts of the country and is increasingly involved in regional collaborations to support research in neighboring countries.
The main Centre is in Kilifi County, it is based in  Kilifi District Hospital, serving over half a million people and linking basic studies to clinical applications with local relevance.
%\begin{center}
\subsection{Organizational Structure}
%\end{center}
The program is organized into five broad departments; there is considerable crossover and interaction between the groupings, with many researchers being members of more than one department. The departments are listed below;
\begin{itemize}
\item Research support
\item  Public Health Research 
\item Pathogens, vectors and Host, Biology
\item  Epidemiology and Demography
\item Clinical Research
\end{itemize}
\subsection{Core Values}
%\begin{center}
\section*{Accountability}
%\end{center}
As diligent stewards of public trust and public funds, they act decisively and compassionately in service to the people’s health. They ensure that their research and services are based on sound science and meet real public needs to achieve public health goals. 
%\begin{center}
\section*{Innovativeness}
%\end{center}
They are committed to promoting and supporting creativity.To ensure the country’s capacity to conduct multidisciplinary research is strong, sustainable and internationally competitive.
%\begin{center}
\section*{Respect and Fairness}
%\end{center}
KWTRP understands and values interdependence with all people, both inside the program and thought the world. They value and treat people’s contributions with dignity. They are committed to achieving a diverse workforce at all levels of the organization and highly embrace cultural diversity.

\subsection{Objectives}
KWTRP bases its operations under the following objectives
\begin{itemize}
\item To carry out research to the highest international scientific and ethical standards on major causes of morbidity and mortality in Africa
\item To build strong and sustainable internationally competitive, national and regional research capacity;
\item To work in a way that facilitates integration and cross fertilization of scientific disciplines;
\item To conduct intervention research and basic research in parallel and to have a direct input to local and international health policy

\end{itemize}
\vspace{15.cm}\section{CHAPTER TWO}
\subsection{Programs Run by the Organization}
Initially, most activities focused on the major public health problem of malaria. Although malaria remains one of the priorities, child and maternal health, HIV/AIDS and other several emerging infections program  are also primary now
%\begin{center}
\subsection{ Malaria Program}
%\end{center}
Malaria has always formed a central theme for  KWTRP. The research covers the whole spectrum of research from basic biology, understanding immunity and disease, clinical trials of new drugs and vaccines, through community based studies to large scale mapping of malaria transmission and control efforts in many countries across Africa. 
 %\begin{center}
%\section*{Establishing  Malaria Human Challenge Facility in Kenya}
%\normalsize
%\end{center}
%The PVHB research group is establishing a facility for experimental human challenge with malaria with colleagues at the KEMRI Centre for Clinical Research in Nairobi.  Carefully controlled challenge will allow both the study of experimental vaccines and the better understanding of how humans make an immune response to malaria.  
%\begin{center}
\subsection{HIV/AIDS Program}
%\end{center}
By 2012 it was estimated that 1.2 million people are infected by HIV in Kenya, HIV affects all segments of the society .transmission has been studied among people at higher risk of infection and its estimated that up to 50$\%$ of new infections are people who got  HIV by themselves.  KWTRP therefor focuses on diagnosing adults with HIV infection, improvement drug regimens and support to take life-long drugs.
%\begin{center}
%\section*{Dynamics and Constraints of Early Infant Diagnosis of HIV  in Rural Kenya}
%\normalsize
%\end{center}
%Cohort design was used to determine uptake and drop out of 213 HIV-exposed infants. Observation and in-depth interviews were conducted through service providers and care givers. 145 (68$\%$) infants enrolled after 2  months of age. 139 (65$\%$) dropped out before follow up to 18 months old. \\ 60 (43$\%$) drop outs occurred within 2 months of enrolment. Maternal factors associated with infant drop out were maternal loss to follow up 
\subsection{Maternal and Perinatal Health}%\normalsize
%\end{center}
%\subsection
%\begin{center}
%\section*{Improving Maternal and Infant Mortality} 
KIPMAT aims to determine the burden and risk factors for adverse maternal and newborn outcomes in Kilifi. They are assessing the effects of HIV, maternal nutrition, malaria infection, bacterial infection, anemia and other risk factors on maternal and infant morbidity and mortality.  Longer term morbidity and survival of mothers and infants, and the later consequences to children’s health is monitored through the KHDSS.
%\subsection
%\begin{center}


%\subsection
%\begin{center}

%\begin{center}
%\end{center}
\vspace{16.0cm}
\section{CHAPTER THREE}
\subsection{Information Regarding Attachment}
Industrial attachment is a course offered as part of degree of B.Sc. Applied statistics with IT under the code SAS 317 in Maseno University. It’s offered to expose students to the working environment, to give students a chance to apply the knowledge gained during the course and to interact with potential employers. I did my attachment at KWTRP in the department of statistics under the supervision of Dr. Greg Fegan .during that period I underwent a lot of training under the directives of my supervisor and other members of the statistics department.
%\begin{center} 
\subsection{Objectives of Attachment}
%\end{center}
\begin{itemize}
\item Enable students  to meet challenges that are related to their field of specialization and learn way to effectively counter them
\item Enable students acquire the necessary work ethics by observing how professionals relate and closely interacting with them
\item	Give the students a chance to put into practice the concept learnt during the course and relate their relevance to the working environment
\item	Identify areas of weakness with an aim of improving on them in future
\item	To expose students to the improved technology advancement in the job market and  the new developments in data analysis technics
\end{itemize}
%\begin{center}
\subsection{Duties}
%\end{center}
\begin{itemize}
\item	Taking online courses 
\item	Data analysis, management and presentation using R, R-Studio and Stata.
\item	Data management for surveys using epidata
\item Assisted in any other duties given by the supervisor
\end{itemize}

%\begin{center}

\subsection{Skills Acquired}
%\end{center}
\begin{itemize}
 \item Observed application of statistics in health research
\item	Data analysis, management and presentation using R, R-studio and Stata.
\item	Data management for surveys using epidata
\item	Record changes to files( version control) using git and GitHub
\item	Report and presentation generation using LaTeX in R-studio
\end{itemize}

%\begin{center}
\section*{Taking Online Courses}
%\end{center}
There are massive open online courses over the internet on variety of topics and approximately 40 MOOC’s providers. In the first week I took an online R course offered by Karolinska Institute on Edx It involved exploring statistics using R. I finished successfully and earned an Honor Code Certificate . I also did  an epidemiology course offered by University of North Carolina on Coursera. This showed the close relationship between statistics and public health and application of statistics in health research. I also did a course on Data Scientist Tool Box offered by Johns Hopkins University. It covered what is required for proper analysis, reproducible research, machine learning, R packages, R tools and introduction to Git and GitHub. 

\section*{Details of Skills Acquired}
%\end{center}
%\begin{center}

 \section*{Observed Application of Statistics in Health Research}
%\end{center}
I attended a seminar on malaria control conducted in Ethiopia using the heads of families as the intervention. From the presentation I identified how the researcher applied statistical knowledge to analyze his data which involved formulation of hypothesis using p-value to make conclusions. I also took a self-paced course on epidemiology offered by university of North Carolina. Through the course I identified how health researchers apply statistics in answering their research questions. Their research works  include

\section*{Measure of Health Outcome}
Health outcome is the impact healthcare activities have on people — on their symptoms,ability to do what they want to do and on whether they live or die. It include whether a given disease process gets better or worse. It focuses not on what is done for patients but what results from what is done. Health outcome can be measured through:

 \section*{Measure of Frequency:} It characterizes the occurrence of health outcomes, in a population.
These measures are descriptive in nature and indicate how likely one is to develop a health outcome in a specified population. The measures of frequency are prevalence, risk, rates and odds.

 \section* {Prevalence:}
Prevalence is the proportion of a population who has the health outcome at a given period of time. It is generally the preferred measure when it is difficult to define onset of the health outcome or any disease of long duration. There are point and period prevalence difference being time factor. 
\section*{Risk:}
It’s the measure of the probability of unaffected individual developing a specified health outcome over a given period of time. Risk is measured in prospective studies since population at risk can be defined at the start of the study. 
 
\section*  {Odds:}
It’s the ratio of the probability that health outcome will occur to the probability that the health outcome will not occur. It’s used mostly in case-control studies and can easily be interpreted by both clinicians and lay-people. 
\section*	{Rates:} 
It’s the measure of how quickly the health outcome is occurring in a population.
\section*{Measure of Association:} They are utilized to compare the association between a specific exposure and health outcome and can also be used to compare two or more populations, those with differing exposure or health outcome status, to identify factors with possible etiological roles in health outcome onset.
\section*	{Risk Difference:}
It provides the difference in risk between two groups indicating how much excess risk is due to the exposure of interest. Positive difference indicates excess risk due to the exposure while a negative difference shows that exposure has protective effects against outcome. 
\section*	{Risk Ratio and Rate Ratio:}
They are normally used in cohort studies. They are measures of strength association between exposure and outcome. Risk ratio is the ratio of risk in the exposed group to the risk in the unexposed group. Rate ratio is the ratio of rates in the exposed group to the rates in the unexposed group.
\section*{Odds Ratio:}
It’s used in place of risk ratio and rate ratio in case-control studies, An odds ratio may approximate the risk ratio or rate ratio in instances where the health outcome prevalence is low  and specific sampling techniques are utilized 
\section*	{Null value}
The null value is a number corresponding to  no association between exposure and the health outcome. In epidemiology, the null value for a risk ratio or rate ratio is 1.0, and it is also 1.0 for odds ratios and prevalence ratios.  Statistical testing focuses on the null hypothesis, which is a statement predicting that there will be no association between exposure and the health outcome.
\section* {Measure of precision}
 
\section*{Confident Interval:}
A confidence interval expresses the extent of potential variation in a point estimate .This variation is attributable to the fact that  point estimate of the mean or risk ratio, rate ratio, or odds ratio is based on some sample of the population rather than on the entire population. The confidence interval also provides information about how precise an estimate is.  Larger sample sizes will provide a more precise estimate. 
\section*{Measure of Significance}

 \section*{The p-value:} The "p" value is an expression of the probability that the difference between the observed value and the null value has occurred because of sampling variability. The smaller the "p" value, the less likely the probability that sampling variability accounts for the difference.  A "p" value less than 0.05, is used as the decision point If the "p" value is less than 0.05, the observed risk ratio, rate ratio, or odds ratio is often said to be "statistically significant.
% \begin{center}
\section* {2. Data Analysis, Management and Presentation Using R}

%\end{center}
R is a free software programming language and software environment for exploration, describing and analyzing data.  To use R effectively it’s important to learn how to use built-in help system, inputting programs and outputting results. For quality output there is a section on packages and GUI that are developed for R.
%\large
\section*{R workspace}
%\normalsize

Every R session takes place in a working directory. For every analysis it’s good to create a new working directory.\emph Setwd ( ), \emph getwd ( ),\emph dir ( )
\section*{Packages}
%\end{center}
Packages are collection of R functions, data and compiled code. Library is the directory where packages are stored. R has standard packages others are available for download and installation. Once installed, they are load into the working session to be used. 

%\begin{center}
\section*{R Graphical User Interface}
%\end{center}
R has a command line interface which allows direct control on calculation and is flexible.
 Commands are entered at the prompt.commands are executed one at time or using the r script several commands can be executed at the same time.

\section*	{Data Presentation}
%\normalsize
Putting results of experiments into graphs, charts and tables is the best way to show the data to others since reading lots of numbers does little to convey the message. It’s also the best way to visualize your data and make proper interpretations. Data presentation before analysis helps to visualize distribution of various variables and select the best analysis to be done. Data may be presented in the form of:\\
\begin{minipage}[t]{0.5\textwidth}

\begin{itemize}
%\begin{flushright}
\item  boxplot 
\item	pie Chart
\item Histogram
\item Table 
%\end{flushright}
\end{itemize}

\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\begin{itemize}
%\begin{flushleft}
\item	Scatter plots
\item Bar charts
\item	Dot chart
\item Frequency polygon
%\end{flushleft}
\end{itemize}
\end{minipage}
%\large
\section*{Data Management}
%\normalsize
I learnt how to manage data using R program. This includes:
\begin{itemize}
\item	Importing data into R from SPSS, SAS, STATA, internet and excel
\item 	Using R functions to create and record variables
\item 	Sorting and merging datasets
	\item Aggregating and reshaping data.
\item 	Subsetting datasets.
\end{itemize}
%\large
\section*	{Exploration of Data}
%\normalsize
Data exploration helps to focus on the relevant data before analysis begins.   This helps when you begin your analysis since you organize your findings and focus on the relevant aspect of your analysis. 
\section*{Statistical analysis using R program}
%\normalsize
Through the Edx course I did analysis of parametric and non parametric test. 
\begin{itemize}
\item One sample t-test: it’s used to compare statistical mean for normally distributed variable to compare the mean to a hypothesized mean.
\item Welsh two sample t-test: it compares the means of two independent normally distributed variables and show if there is a difference in the means when the variances are unequal 
\item Two sample t-test:  it compares the means of two independent normally distributed variables and show if there is a difference in the means when the variances are equal.
\item Pairwise t-test: it compares the means of two dependent normally distributed variables showing if there is a difference in the two means
\item ANOVA test: it used to compare means of more than two samples and show if there is a difference in means. 
\item Wilcoxon rank-sum test: it’s an alternative to the Group Wise t-test
\item Wilcoxon signed-rank test: it’s an alternative for the pairwise t-test
\item Kruskal-wallis: the non-parametric alternative for ANOVA test
\end{itemize}
\section*{R-studio}

R-Studio is an integrated development environment for R.   it is especially well integrated with literate programming tools for reproducible research. R-Studio is available in two editions: R-Studio Desktop, where the program is run locally as a regular desktop application; and R-Studio Server, which allows access to R-Studio using a web browser. 

\section* {R-studio layout}
There are default windows that shows up when R studio is open 
\begin{itemize}
\item Console: it functions basically the same way as the console in R
\item History/ workspace: history pane records all the commands run it allows return to a code and insert it into a code source file while workspace shows all the objects in your workspace and their characteristics.
\item Files/Plots/Packages/Help: file pane helps to see and organize your file. Plot pane is where figures created in R appear. Packages pane shows the packages 
installed and help pane shows the help file.
\item Source pane: this pane allows creating, editing and running your source code files it functions as an editor and forms the basis of reproducible research in R-studio. Source pane has R source code, R markdown files and R Latex files.
\end{itemize}
\section* {Data Analysis, Management and Presentation Using Stata}
Stata is a powerful statistical package with good data-management facilities, a wide array of statistical techniques, and an excellent system for producing publication-quality graphs.
\section* {Stata Interface}
Stata has five windows command window where commands are typed, results window where the results of your commands are shown, review window which keeps track of used commands, variable window which list variables in your dataset and finally the properties window display properties of the variables. 

\section* {User Graphical Interface}
Stata has GUI which allows selecting commands and options from a menu and dialog box. After point and click Stata types the corresponding command. For reproducible results its better to use a do file instead.


\section* {Help in Stata}
To obtain help on a command or function in Stata help command-name this displays help on viewer window help command-name will display help on results window. If you don’t know command name help search gives a few options.

\section* {Data Presentation in Stata}  
Just like in R data presentation before analysis helps to visualize distribution of variables and select the best analysis to apply. After analysis data presentation helps in proper interpretation and the best and easiest way to show your result to others.

\section*{Data Management Using Stata}
Data management using Stata included:
\begin{itemize}
%\item Importing data into Stata from spreadsheet files
\item	Using functions to create, record and rename variables
\item Sorting and merging datasets
\item	Sub setting datasets and observations.
\item	Appending data files
\end{itemize}
\section*{Data Exploration Using Stata}
It is often the case that some effort must be made to focus your attention on pertinent aspects of your data before true analysis can begin. The key to managing such an exploration is to be organized. Keeping records about the exploration, recording your thoughts and ideas along the way, and organizing your findings are all important. The following procedures are used for exploration of data using Stata
\begin{itemize}
\item Summarize: produces summary statistics for each variable
\item Tabulate:  produces summary statistics of mean and standard deviations for specified variable
\item List: list all the observations for the variable specified
\item Describe: gives the variable name, label and type
\item Codebook: important for showing missing values
\end{itemize}
\section*{Statistical Analysis Using Stata}
Using the in-built datasets I did analysis on several data, some of the analysis involved:\\
•  One sample t-test: A one sample t-test allows us to test whether a sample mean (of a normally distributed interval variable) significantly differs from a hypothesized value.\\ 
•	Paired t-test: A paired (samples) t-test is used when you have two related observations (i.e., two observations per subject) and you want to see if the means on these two normally distributed interval variables differ from one another.\\
•	Wilcoxon signed rank sum test: The Wilcoxon signed rank sum test is the non-parametric version of a paired samples t-test.\\



\section*{Version Control Using Git and GitHub}
git is a distributed version control system which runs at the command line of your local machine. It keeps track of your files and modifications to those files in a repository. GitHub is a web page where you can publish your repositories and collaborate with other people. git saves repositories locally on your machine and using git push command you can send some branches to GitHub. 

\section*{Data Management for Surveys Using Epidata}

Epidata is a program with focus on data entry.  It does not contain any complex data analysis functions but data can be exported to SAS, Stata or other preferences. to create surveys you define database,Database is a file with information about variables such as the name and range with a defined structure. To define database we specify each variable name, type and length. 


        




\section*{Report Generation and Presentation Using LaTeX in R studio}

I learnt how to generate and present reports using R-studio and the beamer class of latex by writing code After the analysis I made a presentation of the analysis using Latex in R studio. This entails writing several lines of code, using packages and theme to come up with  presentable ocuments. The presentation slides are attached at the end of the report.



\section*{Achievements}
From the various activities have been involved in during my Attachment period at KWTRP the following are my achievements:
\begin{itemize}
\item  Data management and analysis using R, R-studio and Stata
•\item	Project presentation using Latex in R-studio 
•\item	Data management for surveys using epidata
•	\item Version control using Git and GitHub
•	\item Professionalism in report writing
\end{itemize}


\section*{Analysis of Survey Data on Development of Virtual Learning Environment at KWTRP}

\section*{Introduction}
     Due to the rising number of young researchers entering the program, the demand for training on basic statistical techniques is increasingly overwhelming such that they are not able to provide sufficient support for it. The internet could help counter this since in the recent development in e-learning, there are plenty of freely available materials in terms of videos and problem sets on various courses. MOOC has added interactive discussion and forums that are helpful in delivering required skills. There are several well financed providers associated with top universities that offer MOOCs. 
\section*{Objective}
To develop a statistical course in an in-house virtual learning environment (VLE) using pre-existing materials from publicly available massive open online courses (MOOCs)

\section*{Method}
First, survey was done on the available online materials that are efficient on statistical skills and courses that are relevant for junior scientist were recommended.  300 questionnaires were generated using Redcap and then sent to program members to get their view on the development. 60 questionnaires were completely answered and used for analysis. 


\section*{Results}

Level of proficiency in statistical analysis\\
To get the level of proficiency in statistical analysis distribution I compared statistical proficiency among the interns and non-interns. I also compared the level of statistical proficiency based on education level. 
     

\section*{MOOCs Use and Experience}
From the survey data I did analysis of those who have used MOOCS before and their experience. Where I found out that  40\% have used MOOCS before. From this I checked for association between  MOOCS use and the learning preference using fishers exact test. From the results  a p-value of 0.94 implies the null hypothesis is to be rejected. There is no propotionality between the two variables.
\section*{Rating}
This shows people views on developing a virtual learning environment within the program rating it as very useful, useful and not useful first among the interns and non-interns.
I also did analysis on project rating basing on level of education rated as very useful, useful, not useful.

\section*{Presentation of Analysis of Survey Data on Development of Virtual Learning Environment at KWTRP}

\includegraphics[width=1.2\textwidth]{page1.png}
\includegraphics[width=1.2\textwidth]{page2.png}
\includegraphics[width=1.2\textwidth]{page3.png}
\includegraphics[width=1.2\textwidth]{page4.png}
\includegraphics[width=1.2\textwidth]{page5.png}
\includegraphics[width=1.2\textwidth]{page6.png}
\includegraphics[width=1.2\textwidth]{page7.png}
\includegraphics[width=1.2\textwidth]{page8.png}
%\includepdf[pages=1-8]{survey.pdf}

\vspace{5.0cm}\section{CHAPTER FOUR}
\subsection{Recommendation and Conclusion}
\section*{To KWTRP}
\begin{itemize}
 \item The organization should continue with the program of training students on statistical skills through MOOCs since it encourages self motivation to explore and learn more.
\item	The statistics department should continue exposing students to statistical software since it helps in applying the theoretical knowledge  
\end{itemize}
\section*{To Maseno University}
\begin{itemize}
\item It would be quite useful to Introduce students to freely available statistical packages such as R early to help nurture statistical skills
	\item It would be beneficial to adjust the course content to include units in  practical statistical analysis and new development in data analysis techniques 
\item	Actively consult prospective employers on necessary courses required for modern statisticians
\end{itemize}
\vspace{6.0cm}\section*{Conclusion}
My attachment at KWTRP was rewarding, I got exposed to several statistical software that raised my interest to learn more on data analysis. MOOCs gave me self motivation to explore and learn more on the respective areas. I was also exposed to real data which I performed analysis to answer various questions. I learnt about various kinds of data used in medical research and how researchers use statistical analysis in their work.\\ I also learnt various general aspects of the work place including how things are organized and how employees interact and conduct themselves. The interaction with members of statistics department, who were proficient in statistics, was both a challenge and a motivation. I achieved my aim to obtain skills that are relevant for modern statisticians. With the available resources I believe subsequent attachees are bound to benefit
 \section*{Appendix}
 \section*{MOOCs Certificate}
\begin{center}
\includegraphics[width=1.45\textwidth]{Certificate.pdf}

\end{center}
%\includegraphics[width=1.45\textwidth]{coursera.png}

\vspace{11.0cm}\section{CHAPTER FIVE}
\subsection{Reference}
www.kemri-wellcome.org\\
www.r-project.org\\
Stata tutorial Princeton 2007 (PDF), Oscar Torres-Reyna
% \section*{Qu}
%\includegraphics{/home/local/KWTRP/jochiel/certificate.pdf}}

 
\end{document}
\end{document}
